name: todo_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.5.2 # docker does not have 3.5.3 as of 28/09/2024

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  rawdog:
    path: ../rawdog
  todo:
    path: ../todo
  postgres: ^3.4.0

dev_dependencies:
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.0
